server:
  port: 8090
spring:
  data:
    mongodb:
#      uri: mongodb://localhost:27017/
      uri: mongodb+srv://21020309:QiFZLO9y3kYOSUuz@memusy.r1j7oeh.mongodb.net/?retryWrites=true&w=majority&appName=memusy
      database: stayevrgoe
      auto-index-creation: true
  output:
    ansi:
      enabled: ALWAYS
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB