server:
  port: 8090
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: stayevrgoe
      auto-index-creation: true
  output:
    ansi:
      enabled: ALWAYS
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB